### ISSUE TITLE
Lazy configuration of test tasks

### ISSUE THREAD

**Issue by tarasgor-allegro** [coditory/gradle-integration-test-plugin#156] opened 2024-11-21 08:13 UTC
## Context

To improve configuration phase of gradle scripts that uses this plugin.

## Expected behavior

If we have the following build script with custom task:

```
plugins {
    ...
    id("com.coditory.integration-test")
}

val customTask by tasks.registering {
    println("Configuring customTask")
    doLast {
        println("Custom task executed")
    }
}

tasks.withType<Test>().configureEach {
    println("Long running configuration....")
}
```

Then executing custom task: `./gradlew customTask`
Should **not** trigger the configuration of all test tasks:

```
❯ ./gradlew customTask
Configuring customTask

> Task :customTask
Custom task executed

BUILD SUCCESSFUL in Xs
```

## Observed behavior

If we have the following build script with custom task:

```
plugins {
    ...
    id("com.coditory.integration-test")
}

val customTask by tasks.registering {
    println("Configuring customTask")
    doLast {
        println("Custom task executed")
    }
}

tasks.withType<Test>().configureEach {
    println("Long running configuration....")
}
```

Then executing custom task: `./gradlew customTask` triggers the configuration of all test tasks:

```
❯ ./gradlew customTask

> Configure project :XXX
Long running configuration....
Configuring customTask

> Task :customTask
Custom task executed

BUILD SUCCESSFUL in Xs
```

* Library version: 2.1.0

**Comment by bgalek** [comment] 2024-11-21 10:59
I would say it's improvement not a bug ;) 
+1 for the idea

**Comment by pmendelski** [comment] 2024-11-26 08:20
@tarasgor-allegro thanks for creating this issue and the draft PR, it was really helpful.

After reading [Gradle lazy configuration](https://docs.gradle.org/current/userguide/lazy_configuration.html) I added/changed some tests to cover the lazy path and found few more corner cases to cover. Thus created and merged a separate PR https://github.com/coditory/gradle-integration-test-plugin/pull/157 

Overall it's a great improvement and an oversight of mine. Please test the newest version `2.2.0` and let me know if all works as intended.

**Comment by bgalek** [comment] 2024-11-26 09:32
NICE! :) I'll be happy to test that out :)

**Comment by tarasgor-allegro** [comment] 2024-11-26 10:24
👍

**Closed** 2024-12-07 11:10 UTC
Labels: bug
